Repository nordtheme/web, pull requests merged in 2019-07, with the labels that each got.

#162 Fix download buttons for Adobe swatches
  content/docs/swatches/index.mdx
Labels: context-documentation, scope-quality, type-bug

#165 Fix typo in hero link for lightline on vim page
  src/components/organisms/page/ports/vim/SectionHero/SectionHero.jsx
Labels: context-documentation, scope-quality, target-nord-vim, type-bug

#161 [WIP] doc improvement
  CHANGELOG.md
Labels: context-documentation, scope-quality, type-improvement

#172 Fix typo in vim plugin support section
  src/components/organisms/page/ports/vim/SectionPluginSupport/SectionPluginSupport.jsx
Labels: context-documentation, scope-quality, scope-ux, type-bug
